---
# tasks file for replace
- name: Check Replace file exist - {{ filename if filename != "NULL" else "filename is not define" }}
  become: "{{ is_sudo|default('yes')}}"
  stat:
    path: "{{ filename }}"
  register: file_exist_result
  when: filename != "NULL"

- name: Debug{{ debug_value }}| File exist result
  debug: var=file_exist_result
  when:
    - is_debug
    - filename != "NULL"
