---
# tasks file for replace
#
#
#- name: Check Replace file exist - {{ filename if filename != "NULL" else "filename is not define" }}
#  become: "{{ is_sudo|default('yes')}}"
#  stat: 
#    path: "{{ filename }}"
#  register: file_exist_result
#  when: filename != "NULL"
#
#- name: Debug{{ debug_value }}| File exist result 
#  debug: var=file_exist_result
#  when: 
#    - is_debug
#    - filename != "NULL"
#
#- name: Include | file exist check
#  include: "{{ role_path }}/tasks/file_exist_check.yml"

- name: Replace "{{ regexp_word }} -> {{ replace_word }}" on {{ filename if filename != 'NULL' else 'filename is not define' }}
  become: "{{ is_sudo|default('yes')}}"
  lineinfile:
    dest: "{{ filename }}"
    regexp: "{{ regexp_word }}"
    line: "{{ replace_word }}"
    #backrefs: yes
    backup: "{{ 'yes' if is_backup else 'no' }}"
  when: 
    - filename != "NULL"
    - file_exist_result.stat.exists
