---
# tasks file for replace
- name: Replace "{{ regexp_word }} -> {{ replace_word }}" on {{ filename if filename != 'NULL' else 'filename is not define' }}
  become: "{{ is_sudo|default('yes')}}"
  lineinfile:
    dest: "{{ filename }}"
    regexp: "{{ regexp_word }}"
    line: "{{ replace_word }}"
    backup: "{{ 'yes' if is_backup else 'no' }}"
  when:
    - filename != "NULL"
    - file_exist_result.stat.exists
